#create artifcats
artifacts_root: artifacts

#data ingestion configuration
data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://github.com/Kili66/Nlp_text_summarization/raw/main/summarizer-data.zip
    local_data_file: artifacts/data_ingestion/data.zip 
    unzip_dir: artifacts/data_ingestion

#data validation configuration
data_validation:
    root_dir: artifacts/data_validation
    STATUS_FILE: artifacts/data_validation/status.txt
    ALL_REQUIRED_FILES: ["train", "test", "validation"] # check if these 3 files are available or not